export const CHANGE_CURRENT_PAGE = "CHANGE_CURRENT_PAGE";
export const CHANG_TOTAL_COUNT = "CHANGE_TOTAL_COUNT";
export const CHANGE_ROOM_LIST = "CHANGE_ROOM_LIST";
export const CHANGE_LOADING = "CHANGE_LOADING";
